### ISSUE TITLE
Pip install fails on Pi

### ISSUE THREAD

**Issue by dkumor** [bastibe/SoundCard#107]
I am maintaining a library that depends on soundcard for audio. Pip installs have started failing for users on the Raspberry Pi (https://github.com/dkumor/rtcbot/issues/16). The error is as follows:
```
Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: https://www.piwheels.org/simple/soundcard/
```

It appears that piwheels no longer hosts wheels of the library for the RasPi - is this something that can be fixed?

**Comment by bastibe** [comment]
Honestly, I always thought it a bit dodgy that the Raspberry Pi is downloading from piwheels instead of PyPI. SoundCard is a pure-python module that works on the Raspberry Pi without modification, so there is no need for the piwheels proxy. You can manually download the wheel from PyPI, and install it using `pip install file-from-pypi.whl`.

**Comment by dkumor** [comment]
I see, I assumed that it was some setting that needed to be set by project maintainers! I'll use this solution for the time-being, thanks!

**Comment by dkumor** [comment]
Oh, actually, I found the problem! While pypi isn't case sensitive, piwheels apparently recently changed to have case-sensitive names, so `pip install soundcard` fails, but `pip install SoundCard` succeeds!

**Comment by bastibe** [comment]
That is terribly annoying. Thank you for finding that out!

**Comment by dkumor** [comment]
I spoke too soon. The issue is case-sensitivity, but it is on piwheel's side. I am opening an upstream issue.
