### ISSUE TITLE
Expose callback events?

### ISSUE THREAD

**Issue by slole** [bastibe/SoundCard#30]
Would it be possible to add support for callback-style recording (the user would just specify the desired chunk size (or not) and provide a function that would be called when there is new data available)? I have been looking through the code and I think I could help implement it, I would just need some pointers on where to start. Also I can only test this on Windows and Linux.

**Comment by bastibe** [comment]
This is a *big* undertaking. I know from experience that implementing these callback interfaces can be quite tricky, and fraught with difficult problems (lack of error signaling, frequent segfaults, timing issues...).

Also, the Windows and Linux side currently do not use the callback interface, so this would require a big re-architecting. The macOS side has some really weird quirks with its callbacks, that we would need to carefully abstract away to make a callback API usable.

And finally, I haven't found callback interfaces to be faster or more reliable than polling interfaces. I would strongly recommend simply using the existing polling interface in a thread, and possibly tie a callback to that instead of using the C callbacks.

But of course I won't stop you, and will try to help wherever I can.

**Comment by slole** [comment]
Thanks for the explanation. I will look into the option of maybe implementing functions that poll gor audio data and call a provided callback function just for the purpose of abstracting polling and providing a more clean interface. If I'll manage to create anything useful I'll create a pull request.

**Comment by RuABraun** [comment]
@bastibe What polling interface? I can't find any info about it in the documentation.

**Comment by slole** [comment]
You could try something like:
```
input = soundcard.all_microphones(include_loopback=True)[self.device]
with input.recorder(self._samplerate, blocksize=self._chunksize) as recorder:
    while not self._stopping:
        data = recorder.record(self._chunksize)
        self._callback(data)
```

**Comment by RuABraun** [comment]
And callback would then do stuff on a separate process is that the idea? My worry is that the second recorder.record() ends you will start skipping samples from the input until you call it again.

Actually I've just realized I can just use concurrent futures with a large enough value for chunk size so that I can do whatever needs to be done before the next buffer is ready.

**Comment by bastibe** [comment]
@slole, thank you, that's exactly what I meant, yes.

@RuABraun, If your processing code takes (potentially) longer than `chunksize`, you might want to put data into a queue, and read that queue from a separate thread.

Be aware, however, that even a separate thread might stall the audio thread enough to drop frames. Audio runs in real time, and real time does not wait for anyone. 

Alternatively, write the data to a file or socket, and read that from a separate process. Then you should be safe from dropouts.
