### ISSUE TITLE
Request: to support python 2.7

### ISSUE THREAD

**Issue by AIIX** [bastibe/SoundCard#4]
Awesome project, this is the only python library that does not depend on port audio and seems to work on ubuntu touch, sailfish OS mobile platform, request to please support python 2.7 i would really like to get this working with https://github.com/MycroftAI/

Also is it possible to set the record time to 2 minutes maximum and save the recorded data to wav file a small example would really help  ! Thanks

**Comment by bastibe** [comment]
I'm sorry, but I don't intend to support Python 2. Since I am a single developer and I am doing this in my spare time, I don't have the time to test everything in more than one programming language. SoundCard is painful to test as it is, what with having to test three separate code paths on three separate operating systems.

That being said, I'd be happy to merge a pull request that improves Python 2 compatibility *IF* it doesn't make the code more complicated.

**Comment by bastibe** [comment]
> Also is it possible to set the record time to 2 minutes maximum and save the recorded data to wav file a small example would really help ! Thanks

I don't understand the question. What exactly are you trying to do?
